
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = sd1_client
SERVER = sd1_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = sd1.x

TARGETS_SVC.c = sd1_svc.c sd1_server.c sd1_xdr.c 
TARGETS_CLNT.c = sd1_clnt.c sd1_client.c sd1_xdr.c 
TARGETS = sd1.h sd1_xdr.c sd1_clnt.c sd1_svc.c sd1_client.c sd1_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g -pthread -DRPC_SVC_FG
LDLIBS += -lnsl
RPCGENFLAGS = -C

# Targets 

all : $(CLIENT) $(SERVER)
	gcc -o socket_client socket_client.c
$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

