/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "sd1.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

float *
averagefunc_1(N_array *argp, CLIENT *clnt)
{
	static float clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, averagefunc,
		(xdrproc_t) xdr_N_array, (caddr_t) argp,
		(xdrproc_t) xdr_float, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

min_max *
minmaxfunc_1(N_array *argp, CLIENT *clnt)
{
	static min_max clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, minmaxfunc,
		(xdrproc_t) xdr_N_array, (caddr_t) argp,
		(xdrproc_t) xdr_min_max, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nProd *
productfunc_1(a_N_array *argp, CLIENT *clnt)
{
	static nProd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, productfunc,
		(xdrproc_t) xdr_a_N_array, (caddr_t) argp,
		(xdrproc_t) xdr_nProd, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
